# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spoon & Birdcage
email: spoonandbirdcage@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Spoon & Birdcage: Portfolio of Barrett A. Long. Artist/Design/Developer/Other Things
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spoonandbirdcage.com" # the base hostname & protocol for your site
twitter_username: SpoonBirdcage
github_username:  SpoonAndBirdcage

# Build settings
markdown: kramdown
